# Site settings
title: The HU Arcade
email: hudevclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huarcade.xyz" # the base hostname & protocol for your site

# color
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  dark-grey: 666

# Team names, titles and social links
people:
- name: Austin Barrett
  pic: 1
  position: Project Manager
  social:
    - title: github
      url: http://github.com/viruscmd
    - title: tumblr
      url: http://art.austinisa.ninja
    - title: chrome
      url: http://austinisa.ninja

- name: Bobby Klein
  pic: 2
  position: University Liaison
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sam Heybey
  pic: 3
  position: Lead Developer
  social:
    - title: github
      url: http://github.com/sheybey
    - title: chrome
      url: http://workofbobby.com/
    # - title: google-plus
    #   url: #

- name: Henry Schmale
  pic: 4
  position: Cabinet Architect
  social:
    - title: github
      url: http://github.com/hschmale16
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #

- name: Danny Ockershausen
  pic: 5
  position: Lead Designer
  social:
    - title: twitter
      url: http://twitter.com/ockershausen
    - title: facebook
      url: http://www.facebook.com/dyanna.ockershausen
    - title: linkedin
      url: http://www.linkedin.com/in/dyanna-ockershausen-6b1936a8

- name: Tim McKenna
  pic: 6
  position: Academic Adviser
  social:
    - title: twitter
      url: https://twitter.com/azraelgroup
    - title: linkedin
      url: http://www.linkedin.com/in/timothyfxmckenna
    - title: facebook
      url: http://www.facebook.com/timothy.mckenna.31
    - title: chrome
      url: http://azraelgroup.com/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/arcadehu
  - title: facebook
    url: http://www.facebook.com/thehuarcade/
  - title: bitbucket
    url: http://bitbucket.org/hudevelopmentclub
  - title: github
    url: http://github.com/hudevelopmentclub
  - title: university
    url: http://harrisburgu.edu

# Postal address (add as many lines as necessary)
address:
  - line: 326 Market St.
  - line: Harrisburg PA, 17101

# Build settings
markdown: kramdown
permalink: pretty
