# Site settings
title: The HU Arcade
email: hudevclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huarcade.xyz" # the base hostname & protocol for your site

# color
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  dark-grey: 666


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: chrome
    url: http://humaker.club
  - title: twitter
    url: http://twitter.com/arcadehu
  - title: facebook
    url: http://www.facebook.com/thehuarcade/
  - title: bitbucket
    url: http://bitbucket.org/hudevelopmentclub
  - title: github
    url: http://github.com/hudevelopmentclub
  - title: university
    url: http://harrisburgu.edu

# Postal address (add as many lines as necessary)
address:
  - line: 326 Market St.
  - line: Harrisburg PA, 17101

# Build settings
markdown: kramdown
permalink: pretty
